"""empty message

Revision ID: 57a331a3c840
Revises: 
Create Date: 2024-10-24 09:39:30.135336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a331a3c840'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_block_bot', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_user_id')
    )
    op.create_table('vacancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('salary', sa.String(), nullable=False),
    sa.Column('is_no_exp', sa.Boolean(), nullable=False),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('employer', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_tag', sa.String(), nullable=False),
    sa.Column('is_no_exp', sa.Boolean(), nullable=False),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('user_tg_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_tg_id'], ['user.tg_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriber')
    op.drop_table('vacancy')
    op.drop_table('user')
    # ### end Alembic commands ###
